branches:
  only:
  - master

services:
  - docker

env:
  global:
  - DOCKER_IMAGE=gastongonzalez/kubia
  - DOCKER_USERNAME=gastongonzalez

script:
  - docker build -t "$DOCKER_IMAGE" .

after_script:
  - docker images

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag "$DOCKER_IMAGE" "${DOCKER_IMAGE}:latest"

deploy:
  provider: script
  script: docker push "${DOCKER_IMAGE}:latest"
  on:
    branch: master
